---
- name: ping test
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: ping target host
      ping:

    - name: check hostname
      command: hostname
      register: hostname_output

    - name: Display hostname
      debug:
        var: hostname_output.stdout  