---
- name: ping test
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: ping target host
      ping:

    - name: user creation
      user:
        name: thahath
        state: present

    - name: Verify user
      command: id thahath
      register: user_details

    - name: Display user_details
      debug:
        var: user_details.stdout        