---
- name: Check Disk Space
  command: df -h /
  register: disk_space
  changed_when: false
- name: Display Disk Space
  debug:
    var: disk_space.stdout_lines
- name: Update Packages on RedHat
  dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
- name: Update Packages on Ubuntu
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Ubuntu"