---
- name: Install packages on RedHat
  dnf:
    name: "{{ packages_to_install }}"
    state: present
  when: ansible_os_family == "RedHat"
- name: Install packages on Ubuntu
  apt:
    name: "{{ packages_to_install }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"