---
- name: Check Chrony Sources
  command: "{{ chrony_command }}"
  register: chrony_sources
  changed_when: false
- name: Check DNS Configuration
  command: cat /etc/resolv.conf
  register: dns_check
  changed_when: false
- name: Display Chrony Output
  debug:
    var: chrony_sources.stdout_lines
- name: Display DNS Output
  debug:
    var: dns_check.stdout_lines