---
- name: Get Group Members
  ansible.windows.win_shell: |
    Get-LocalGroupMember -Group "{{ group_name }}"
  register: group_members
- name: Display Group Members
  debug:
    var: group_members.stdout_lines