---
- name: Check Chrony Sources
  command: chronyc sources -v
  register: chrony_sources
  changed_when: false
- name: Check DNS Configuration
  command: cat /etc/resolv.conf
  register: dns_check
  changed_when: false
- name: Display Chrony Output
  debug:
    var: chrony_sources.stdout_lines
- name: Display DNS Output
  debug:
    var: dns_check.stdout_lines
- name: Check Current Timezone
  command: timedatectl show --property=Timezone --value
  register: timezone_check
  changed_when: false
- name: Display Timezone
  debug:
    var: timezone_check.stdout