---
- name: Delete Local User
  ansible.windows.win_user:
    name: "{{ user_name }}"
    state: absent
- name: Verify User Removal
  ansible.windows.win_shell: |
    Get-LocalUser -Name "{{ user_name }}"
  register: deleted_user
  ignore_errors: true
- name: Display Verification Result
  debug:
    var: deleted_user.stderr_lines