---
- name: Check Service Status
  command: systemctl is-active {{ item }}
  loop: "{{ critical_services }}"
  register: service_status
  changed_when: false
- name: Display Service Status
  debug:
    msg: "{{ item.item }} : {{ item.stdout }}"
  loop: "{{ service_status.results }}" 